backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/img
public_folder: "/img" # The src attribute for uploaded media will begin with /img

collections:
  - name: "episode" # Used in routes, e.g., /admin/collections/blog
    label: "Episode" # Used in the UI
    folder: "content/episodes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index" # Filename template
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "episode"}
      - {label: "Title of the episode ex: 'Season 1 Episode 1: Ryan Seamy'", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Guest Name ex: 'Ryan Seamy'", name: "guestName", widget: "string"}
      - {label: "Guest Photo", name: "guestPhoto", widget: "image"}
      - {label: "Slug ex: 'ep1'", name: "slug", widget: "string"}
      - {label: "Vimeo video episode number (found in the vimeo url) ex: '430343600'  ", name: "vim_ep_num", widget: "string"}
      - {label: "Buzzsprout audio episode number (found in the buzzsprout url) ex: '4343081' ", name: "buz_ep_num", widget: "string"}
      - {label: "Show Notes (copied from buzzsprout page)", name: "shownotes", widget: "markdown"}
      - {label: "Podcast Transcript (copied from buzzsprout page)", name: "transcript", widget: "markdown"}